services:
  arcadedb:
    image: arcadedata/arcadedb:latest
    ports:
      - "2480:2480"
      - "7687:7687"
    environment:
      JAVA_OPTS: >-
        -Darcadedb.server.rootPassword=playwithdata
        -Darcadedb.server.plugins=Bolt:com.arcadedb.bolt.BoltProtocolPlugin
        -Darcadedb.profile=low-ram

      ARCADEDB_OPTS_MEMORY: "-Xms96M -Xmx128M"

    cpus: 0.5
    mem_limit: "256m"
    volumes:
      - arcadedb_data:/home/arcadedb/databases
    restart: on-failure

volumes:
  arcadedb_data:
